# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-HTML-Content
version:      0.07
version_from: lib/Test/HTML/Content.pm
installdirs:  site
requires:
    HTML::TokeParser:              0
    Test::Builder:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
